### PR TITLE
👷‍♀️ Swap count_as_decoded/encoded

### PR DESCRIPTION
**Pull request by nickelpro**
These appear to have been mixed up

### CODE REVIEW

**Comment by ThePhD** [comment]
I... don't seem to have tests on PRs going. Can you check that it's producing the right values and the tests are okay? (Asides from the obvious rename.)

**Comment by ThePhD** [comment]
I can't seem to re-start the tests on this PR, since I guess I pushed that change too late to the workflow.

Just make sure an invocation of the typical build  and `ctest` works out okay, only on your computer should be fine enough!

**Comment by nickelpro** [comment]
All green
```
[build] Starting build
[proc] Executing command: "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.EXE" --build c:/Users/nicke/source/repos/text/build/Debug --config Debug --target all --
[build] [1/2   0% :: 0.000] Re-checking globbed directories...
[build] ninja: no work to do.
[build] Build finished with exit code 0
[proc] Executing command: ctest -j14 -C Debug -T test --output-on-failure
[ctest]    Site: DESKTOP-LK6L3GD
[ctest]    Build name: Win32-ninja
[ctest] Create new tag: 20220320-2052 - Experimental
[ctest] Test project C:/Users/nicke/source/repos/text/build/Debug
[ctest]     Start 6: ztd.text.tests.compile_fails.encode_lossy.cpp
[ctest]     Start 5: ztd.text.tests.compile_fails.decode_lossy.cpp
[ctest]     Start 7: ztd.text.tests.compile_fails.transcode_lossy.decode.cpp
[ctest]     Start 8: ztd.text.tests.compile_fails.transcode_lossy.encode.cpp
[ctest]     Start 2: ztd.text.tests.basic_run_time
[ctest]     Start 1: ztd.text.tests.inclusion
[ctest]     Start 4: ztd.text.tests.tiny_buffer
[ctest]     Start 3: ztd.text.tests.basic_compile_time
[ctest] 1/8 Test #1: ztd.text.tests.inclusion ..................................   Passed    0.04 sec
[ctest] 2/8 Test #3: ztd.text.tests.basic_compile_time .........................   Passed    0.02 sec
[ctest] 3/8 Test #4: ztd.text.tests.tiny_buffer ................................   Passed    0.04 sec
[ctest] 4/8 Test #2: ztd.text.tests.basic_run_time .............................   Passed    0.33 sec
[ctest] 5/8 Test #5: ztd.text.tests.compile_fails.decode_lossy.cpp .............   Passed    0.99 sec
[ctest] 6/8 Test #7: ztd.text.tests.compile_fails.transcode_lossy.decode.cpp ...   Passed    0.98 sec
[ctest] 7/8 Test #8: ztd.text.tests.compile_fails.transcode_lossy.encode.cpp ...   Passed    0.98 sec
[ctest] 8/8 Test #6: ztd.text.tests.compile_fails.encode_lossy.cpp .............   Passed    1.07 sec
[ctest] 
[ctest] 100% tests passed, 0 tests failed out of 8
[ctest] 
[ctest] Total Test time (real) =   1.08 sec
[ctest] CTest finished with return code 0
```

**Comment by ThePhD** [comment]
Thanks!

**Pull request merged**
