### PR TITLE
MAINT: renormalize line endings

### PR DESCRIPTION
**Pull request by h-vetinari**
If VSCode messes up the line endings relative to the `.gitattributes` settings discussed [previously](https://github.com/soasis/text/pull/35), perhaps a solution could be to do `git add --renormalize .` before creating the next mega commit. 🙃 

PS. Advise not to squash, otherwise https://github.com/soasis/text/pull/37/commits/c83af0643ebeff57adac1346614d4126428100e8 won't take effect.

### CODE REVIEW

**Comment by ThePhD** [comment]
I should really get vscode to stop doing this to the line endings. I have no idea why it **does** keep doing it. All of my git settings are consistent.

**Comment by h-vetinari** [comment]
From 1k mangled line endings back to ~14k 🙃

**Comment by ThePhD** [comment]
Sorry. If I could figure out what exactly was destroying the line endings (extension or whatever) I'd turn it off. There's no vscode setting I can find obviously responsible for this.

**Comment by h-vetinari** [comment]
I still think that there's probably some way of tweaking `.gitattributes` to get things to behave correctly - e.g. I just [found](https://stackoverflow.com/questions/71081340/prevent-vscode-to-crlf-files) this SO answer that seems to describe a similar situation. 

Alternatively, it may work to add a git hook that just does `git add . --renormalize` every time you commit something. That wouldn't necessary be helpful for adding (c)hunks incrementally (`git add . -p` etc.), but then you're more of the school of mega commits anyway. 😆

**Comment by h-vetinari** [comment]
Oooooh, more googling goodness: it might work to set `"files.eol": "\n",` in `.vscode/settings.json` (see [here](https://blog.boot.dev/clean-code/line-breaks-vs-code-lf-vs-crlf/))

**Comment by ThePhD** [comment]
I did the whole renormalization. (Sorry for trampling over this commit.)

Hopefully this is the last time I have to do this for all these repositories.

**Pull request closed without merging**
